   # Check https://goreleaser.com/customization/env/
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

# Check https://goreleaser.com/customization/hooks/
before:
  hooks:
  - go mod download

# Check https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
        gomips: hardfloat
    # Run upx after build finished

# Check https://goreleaser.com/customization/archive/
archives:
  - name_template: "pita_{{ .Version }}_{{ .Os }}_{{ .Arch }}"  
    replacements:
      amd64: x86_64

project_name: pita

nfpms:
  - license: "Apache 2.0"
    maintainer: "dotunj"
    homepage: "https://github.com/dotunj/pita"
    description: "Binary Distribution for Pita"
    formats:
      - apk
      - rpm
      - deb


# Check https://goreleaser.com/customization/homebrew/
brews:
  - name: pita
    homepage: 'https://github.com/dotunj/homebrew-pita'
    description: 'Binary Distribution for Pita'
    commit_author:
      name: dotunj
      email: dotunj@gmail.com
    tap:
      owner: dotunj
      name: homebrew-pita