# Check https://goreleaser.com/customization/hooks/
project_name: pita

before:
  hooks:
    - go mod download
    - go mod tidy

# Check https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

# Check https://goreleaser.com/customization/archive/
archives:
  - name_template: "pita_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64

nfpms:
  - id: debrpm
    license: "Apache 2.0"
    maintainer: "dotunj"
    homepage: "https://github.com/dotunj/pita"
    description: "Binary Distribution for Pita"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - rpm
      - deb

  - id: apk
    license: "Apache 2.0"
    maintainer: "dotunj"
    homepage: "https://github.com/dotunj/pita"
    description: "Binary Distribution for Pita"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - apk

checksum:
  name_template: "{{ .ProjectName}}_checksums.txt"
