# Check https://goreleaser.com/customization/env/

project_name: pita

# Check https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod download

# Check https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
        gomips: hardfloat
    # Run upx after build finished

# Check https://goreleaser.com/customization/archive/
archives:
  - name_template: "pita_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
    files:
      - VERSION

nfpms:
  - id: debrpm
    license: "Apache 2.0"
    maintainer: "dotunj"
    homepage: "https://github.com/dotunj/pita"
    description: "Binary Distribution for Pita"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - rpm
      - deb

  - id: apk
    license: "Apache 2.0"
    maintainer: "dotunj"
    homepage: "https://github.com/dotunj/pita"
    description: "Binary Distribution for Pita"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - apk

publishers:
  - name: fury.io
    ids:
      - debrpm
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/pera/

# Check https://goreleaser.com/customization/homebrew/
brews:
  - name: pita
    homepage: "https://github.com/dotunj/homebrew-pita"
    description: "Binary Distribution for Pita"
    commit_author:
      name: dotunj
      email: dotunj@gmail.com
    tap:
      owner: dotunj
      name: homebrew-tools
